### ISSUE TITLE
User menu doesn't show on mobile

### ISSUE THREAD

**Issue by ghost** [CodyHouse/cd-mercurio-changelog#1]
Hi,

In your demo, the user menu is not show on mobile.

![account-settings](https://user-images.githubusercontent.com/8331297/86475470-073c3200-bd45-11ea-9855-3ff2f29ede21.jpg)

**Comment by sebastiano-guerriero** [comment]
Hi there!

True! We'll look into it. In the meantime, you can customize the navigation bu adding/removing menu items.

For example, if you want to add a link to the account section (visible only on small screens):

```html
<!-- 👇 link -->
<li class="mega-nav__item">
  <a href="https://codyhouse.co/ds/docs/templates" class="mega-nav__control" target="_blank"
    rel=”noopener”>Docs</a>
</li>

<li class="mega-nav__item hide@md">
  <a href="account-settings.html" class="mega-nav__control">Account</a>
</li>
```

Or you can add another "accordion" section on mobile. You can duplicate one of the existing ones and use it as a template. Then you can use the hide@md utility class to hide it on bigger screens.

**Comment by claudia-romano** [comment]
Hi,
we have just released a new version of the template that includes the Account link in the mobile navigation as well:
https://codyhouse.co/template/mercurio

Cheers!
