### ISSUE TITLE
"Your cart" modal of every page, tabindex="-1" should apply to div.modal

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-mercurio-changelog#2]
![image](https://user-images.githubusercontent.com/6344066/86867228-0c163280-c105-11ea-8d57-8fad57924077.png)

**Comment by claudia-romano** [comment]
Hi there, may I ask you why that change should be made? 
The `div.modal__content` is the element that is announced to Screen Readers (it has the `aria-labelledby` and `aria-describedby` attributes) so the focus is moved to that element when the cart is open.

**Comment by dean-shanghai** [comment]
Hi claudia, 
actually two reasons: 
1. https://codyhouse.co/ds/components/app/cart-drawer--modal, it's the same component and the attribute is on the outer element, right?
2. if tabindex="-1" is on the div.modal__content element, when the cart is open, there is a "focus border", just like that shown in the image.

**Comment by claudia-romano** [comment]
Thanks for the clarification, we are looking into it. 
Meanwhile, to remove the focus border, you can add the `.js-tab-focus` class to the `.modal__content` element.

Also, what browser are you using? I'm not able to recreate the focus border effect. Thanks.

**Comment by dean-shanghai** [comment]
Using newest chrome,
focus border is on the Mercurio pages: https://codyhouse.co/demo-templates/mercurio/index.html

**Comment by sebastiano-guerriero** [comment]
Just tested on Chrome Version 84.0.4147.89 (Mac), and the focus ring is not visible if I navigate using the mouse, or if I use the keyboard (screencast attached). Did you try adding the .js-tab-focus class to the .modal__content?

[cart-modal-mercurio.mp4.zip](https://github.com/CodyHouse/cd-mercurio-changelog/files/4923255/cart-modal-mercurio.mp4.zip)

**Comment by dean-shanghai** [comment]
Hi sebastiano, yes add js-tab-focus class works, this is clear here~

My suggestion is that you can update the demo template pages 🤣
![border](https://user-images.githubusercontent.com/6344066/87512402-8583c700-c6a9-11ea-9cd7-75784ad573c3.gif)

**Comment by sebastiano-guerriero** [comment]
oh I see, the ring is visible when you click! We'll look into it and update the demo 👍

**Comment by claudia-romano** [comment]
The focus ring issue has been fixed with the latest version of the template:
https://codyhouse.co/template/mercurio

Cheers!
