### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by lucawieczorek** [CodyHouse/cd-mercurio-changelog#3]
Error in Navbar while opening dropdown on Desktop **not on mobile** version!

Uncaught TypeError: Cannot read property 'classList' of undefined
    at Function.Util.hasClass (scripts.js:9)
    at closeSearch (scripts.js:5774)
    at setMegaNavLayout (scripts.js:5733)
    at initMegaNav (scripts.js:5712)
    at new MegaNav (scripts.js:5708)
    at scripts.js:5891
    at scripts.js:5891
    at scripts.js:5927

**Comment by claudia-romano** [comment]
Hi there,
could you please provide the steps to reproduce this issue? I am not able to reproduce it using our demo:
https://codyhouse.co/demo-templates/mercurio/index.html

Thank you

**Comment by lucawieczorek** [comment]
Hello Claudia,

you can see it under https://wessling-allianz.de/beta/1/main/

It is only on the index.html. Sometimes it works, sometimes it does not.

**Comment by claudia-romano** [comment]
Hi Luca, 
the link you provided does not work. Please be aware that we won't be able to check for bugs when the template is part of a custom complex project.

If you could please provide a test case where you can recreate the bug starting from our template and, for example, modifying the content to use your custom one. We won't be able to check the bug if additional custom js/css has been added to the template. Thanks.

Cheers,
